# HAL MCP configuration for Kavedarr
[mcp_servers.hal]
command = "npx"
args = ["-y", "hal-mcp"]
startup_timeout_sec = 20
tool_timeout_sec = 120

env = {
    "HAL_BASE_URL" = "http://127.0.0.1:7878",
    "HAL_DEFAULT_HEADERS" = "{\"X-Api-Key\": \"{secrets.HAL_SECRET_KAVEDARR_API_KEY}\"}"
}

# Optional: export HAL_PROFILE="$HOME/kavedarr/docs/hal/hal_profile.json"
