model = "gpt-5"

[subagents]

[[subagents.commands]]
name = "new-spec"
read-only = false
agents = ["code", "gemini", "claude"]
orchestrator-instructions = """
Unified SPEC creation from feature description. Entry point for new features.

Phase 1: Generate SPEC-ID and scaffold
1. Run: python3 scripts/spec_ops_004/generate_spec_id.py "<feature-description>"
2. Store result as SPEC_ID
3. Create directory: docs/${SPEC_ID}/
4. Add SPEC.md table row

Phase 2: Generate PRD (via /specify)
5. Invoke /specify ${SPEC_ID} <feature-description>

Phase 3: Multi-agent planning (via /plan)
6. Invoke /plan ${SPEC_ID}

Phase 4: Task breakdown (via /tasks)
7. Invoke /tasks ${SPEC_ID}

Phase 5: Present package
8. Show summary and ask: "Ready to implement? Run: /spec-auto ${SPEC_ID}"

Never auto-run /spec-auto - always require explicit approval."""

[mcp_servers.repo_search]
command = "uvx"
args = ["awslabs.git-repo-research-mcp-server@latest"]
startup_timeout_sec = 30
tool_timeout_sec = 120

[mcp_servers.doc_index]
command = "npx"
args = ["-y", "open-docs-mcp", "--docsDir", "/home/thetu/code/docs"]
startup_timeout_sec = 20
tool_timeout_sec = 60

[mcp_servers.git_status]
command = "uvx"
args = ["mcp-server-git", "--repository", "/home/thetu/code"]
env = { "GIT_PAGER" = "cat" }
startup_timeout_sec = 20
tool_timeout_sec = 120

[mcp_servers.uniprof]
command = "npx"
args = ["-y", "uniprof", "mcp", "run"]
startup_timeout_sec = 30
tool_timeout_sec = 300

[mcp_servers.hal]
command = "npx"
args = ["-y", "hal-mcp"]
startup_timeout_sec = 20
tool_timeout_sec = 120
