model = "gpt-5"

[mcp_servers.repo_search]
command = "uvx"
args = ["awslabs.git-repo-research-mcp-server@latest"]
startup_timeout_sec = 30
tool_timeout_sec = 120

[mcp_servers.doc_index]
command = "npx"
args = ["-y", "open-docs-mcp", "--docsDir", "/home/thetu/code/docs"]
startup_timeout_sec = 20
tool_timeout_sec = 60

[mcp_servers.shell_lite]
command = "npx"
args = ["-y", "super-shell-mcp"]
startup_timeout_sec = 20
tool_timeout_sec = 300

[mcp_servers.git_status]
command = "uvx"
args = ["mcp-server-git", "--repository", "/home/thetu/code"]
env = { "GIT_PAGER" = "cat" }
startup_timeout_sec = 20
tool_timeout_sec = 120

[mcp_servers.spec_registry]
command = "npx"
args = ["-y", "mcp-proxy", "https://registry.modelcontextprotocol.io/api/sse"]
startup_timeout_sec = 20
tool_timeout_sec = 90
