// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolExposureSurface } from "../ToolExposureSurface";
import type { AppDisabledReason } from "./AppDisabledReason";

export type AppsConfig = { [key in string]?: { enabled: boolean,
/**
 * Additional model-facing surfaces omitted for this connector's tools.
 */
omit_tools_from: Array<ToolExposureSurface> | null, disabled_reason: AppDisabledReason | null, } };
