// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdditionalPermissionProfile } from "./AdditionalPermissionProfile";
import type { CommandAction } from "./CommandAction";
import type { ExecPolicyAmendment } from "./ExecPolicyAmendment";
import type { NetworkApprovalContext } from "./NetworkApprovalContext";

export type CommandExecutionRequestApprovalParams = { threadId: string, turnId: string, itemId: string, 
/**
 * Identifier for this specific approval callback.
 */
approvalId?: string | null, 
/**
 * Optional explanatory reason (e.g. request for network access).
 */
reason?: string | null, 
/**
 * Optional context for a managed-network approval prompt.
 */
networkApprovalContext?: NetworkApprovalContext | null, 
/**
 * The command to be executed.
 */
command?: string | null, 
/**
 * The command's working directory.
 */
cwd?: string | null, 
/**
 * Best-effort parsed command actions for friendly display.
 */
commandActions?: Array<CommandAction> | null, 
/**
 * Optional additional permissions requested for this command.
 */
additionalPermissions?: AdditionalPermissionProfile | null, 
/**
 * Optional proposed execpolicy amendment to allow similar commands without prompting.
 */
proposedExecpolicyAmendment?: ExecPolicyAmendment | null, };
